### ISSUE TITLE
W3ID für KMK-Vocabs

### ISSUE THREAD

**Issue by oellers** [dini-ag-kim/kmk-vocabs#2]
- [x]  W3ID URL für kmk-vocabs einrichten

**Comment by acka47** [comment]
In den Turtle files steht derzeit das hier als gemeinsamer Namespace: `http://w3id.org/comein/`. Ich kenne den Hintergrund dieser Vokabulare nicht und wofür/von wem sie alles benutzt werden sollen. Wenn die Vokabulare in erster Linie für das ComeIn-Projekt sind, sollte das besser in aus der KIM-GitHub-Organisation verschoben werden. Wenn das im KIM-Rahmen veröffentlicht und gepflegt werden soll, sollten wir `http://w3id.org/kim/` nutzen.

**Comment by oellers** [comment]
@sroertgen Wollte dafür noch eine W3ID URL einrichten, #1 wurde etwas zu früh gemergt, die base-url wird aber noch geändert.
Das ComeIn Projekt wird dann die KIM-Werteliste nutzen.

**Comment by sroertgen** [comment]
habe einen entsprechenden Pull Request in unserer w3id-Fork gestellt: https://github.com/dini-ag-kim/w3id.org/pull/1

**Comment by sroertgen** [comment]
Pull Request bei w3id is pending: https://github.com/perma-id/w3id.org/pull/2297

**Comment by sroertgen** [comment]
w3-Weiterleitung ist geschaltet!
