### ISSUE TITLE
Fix base urls

### ISSUE THREAD

**Issue by sroertgen** [dini-ag-kim/kmk-vocabs#3]
Wie in #1 erwähnt müssen die Base URLs angepasst werden.

**Comment by sroertgen** [comment]
Ich würde gerne noch den Namen und die URL für das Vokabular `digitalCompetencies` ändern.

Wir haben jetzt normalerweise immer deutsche Namen für deutsche Wertelisten genommen (bspw. `schulfaecher.ttl`). Ich denke für das Vokabular sollten wir das auch so handhaben.

Was hälst du von `digitale-kompetenzen` @oellers ?

**Comment by oellers** [comment]
Wenn man drüber nachdenkt, sind die Kompetenzen ja nicht digital, sondern digitalisierungsbezogen, also ggf. besser:

1. digitalisierungsbezogene-kompetenzen
2. kompetenzen_digitale-welt
3. kiddw (als Akronym für "Kompetenzen in der digitalen Welt")

Ad hoc Tendenz zu (1), sofern keine bessere Alternative

**Comment by sroertgen** [comment]
> Wenn man drüber nachdenkt, sind die Kompetenzen ja nicht digital, sondern digitalisierungsbezogen

Guter Hinweis, so richtig glücklich war ich damit auch nicht. Dann lass uns erstmal (1) nehmen und wir stellen das auf dem nächsten Treffen nochmal zur Abstimmung
